# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8ed03e12f8b0016bc7409db312310f0ca44343445490e82ddabb1a12f7a5eb01e9a1fd61c7387ba0877c0f763e25e02771d1eb08ac34ed9aa16d4ec5cddb539

test:
  secret_key_base: 8f2822ffb59c96ff4b2fc3c6aab79d4a6590651f679a137758cb422662f25a1c90504e715a1e70ed2bdc3fe072cc0b07c0862c1e8e7053363613ccddacce7efe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
